# Generated by Django 3.0.3 on 2020-02-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summry', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('experto', models.BooleanField(null=True)),
                ('desde', models.DateField(null=True)),
                ('hasta', models.DateField(null=True)),
            ],
        ),
    ]
